POST http://localhost:8080/api/register
Accept: application/json

{
"username": "leoforney",
"email": "forneyleo@gmail.com",
"firstName": "Leo",
"lastName": "Forney",
"password": "password"
}
###

POST http://localhost:8080/api/login
Accept: application/json

{
"username": "leoforney",
"password": "password"
}

###